version: "3"
services:
  react-app:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - todo-app
  api-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - todo-app
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=test_db
      # - MYSQL_USER=dan
      # - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - todo-app
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - todo-app
networks:
  todo-app:
    driver: bridge
volumes:
  my-datavolume:
