version: "3"
services:
  react-app:
    build:
      context: client
      dockerfile: Dockerfile.test
    networks:
      - todo-app
    depends_on:
      - nginx
  api-server:
    build:
      context: server
      dockerfile: Dockerfile.test
    ports:
      - "4000:4000"
    networks:
      - todo-app
    depends_on:
      - mysql
      - redis
      - nginx
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=test_db
      # - MYSQL_USER=dan
      # - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - todo-app
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - todo-app
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - todo-app
networks:
  todo-app:
volumes:
  my-datavolume:
