name: Deploy Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose down
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker ps
