name: Testing React app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose down
      - run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
      - run: docker ps
